name: publish
on: [push]
  jobs:
    publish-docker-image:
      runs-on: windows-latest
      steps:
      - uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
      registry: ghcr.io
      username: ${{ github.actor }}
      password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build the dockeragent Docker image
      run: |
            docker build . --tag ghcr.io/bit-of-faith/dockeragent:latest
            docker run ghcr.io/bit-of-faith/dockeragent:latest
            docker push ghcr.io/bit-of-faith/dockeragent:latest